# Generated by Django 4.0.6 on 2022-08-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_shopingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='items',
            field=models.ManyToManyField(null=True, to='product.product'),
        ),
    ]
