# Generated by Django 4.0.6 on 2022-08-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_shopingcart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_cart',
            field=models.BooleanField(default=False),
        ),
    ]
