# Generated by Django 4.0.6 on 2022-08-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_is_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_cart',
        ),
    ]
