# Generated by Django 4.0.6 on 2022-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel'),
        ),
    ]
